/*ALTERAR COLUNA PARA N�O NULA*/
ALTER TABLE PRODUTOS 
ALTER COLUMN cod_produto
VARCHAR(10) NOT NULL

/*ALTERAR COLUNA COD DO PRODUTO PARA PRIMARY KEY OU CHAVE PRIM�RIA*/
ALTER TABLE PRODUTOS
ADD CONSTRAINT PK_PRODUTOS
PRIMARY KEY CLUSTERED (cod_produto)
