/*PARA FAZER UM JOIN, PRECISAMOS DE UMA CHAVE ÚNICA QUE ESTEJA NAS DUAS OU MAIS TABELA QUE QUEREMOS JUNTAR. 
NÃO PRECISA TER O MESMO NOME, MAS PRECISA TER O MESMO TIPO. CASO NÃO SEJA O MESMO TIPO, É NECESSÁRIO USAR UMA FUNÇÃO DE CONVERTER O TIPO.
NÃO É PRECISO TER UMA CHAVE ESTRANGEIRA LIGANDO OS DOIS CAMPOS. É POSSÍVEL LIGAR 2 CAMPOS DIFERENTES SEM QUE HAJA UMA CHAVE ESTRANGEIRA.
MAS QUANDO HÁ FK(FOREIGN KEY) OU CHAVE ESTRANGEIRA A PERFORMACE DA CONSULTA É MAIS RÁPIDA.*/


SELECT 
		A.NOME
	,	B.CPF
	,	B.DATA
	,	A.BAIRRO
FROM [TABELA DE VENDEDORES] A INNER JOIN [NOTAS FISCAIS] B
ON A.MATRICULA = B.MATRICULA

/*INNER JOIN VAI FAZER A JUNÇÃO DO QUE ESTÁ EM COMUM*/