/*COM LEFT JOIN SERÁ FEITO A JUNÇÃO ENTRE A TABELA DA 'ESQUERDA' COM A TABELA DA 'DIREITA', MAS UM POUCO
DIFERENTE DO INNER JOIN. O LEFT JOIN TRARÁ TODA TABELA DA 'ESQUERDA' E SÓ TRARÁ DA TABELA DA 'DIREITA' O QUE FOR INCOMUM ENTRE ELAS...*/
SELECT 
		A.[NOME]
	,	COUNT(*) 
FROM [TABELA DE CLIENTES] A LEFT JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
GROUP BY A.[NOME]


/*CONSULTA PARA VERIFICAR A RELAÇÃO DOS BAIRROS ENTRE O VENDEDOR E O CLIENTE REMOVENDO OS NULOS(NULL) E ORDENANDO POR ASCENDENTE PELO NOME DO CLIENTE*/
SELECT 
		A.[NOME] 'VENDEDORES'
	,	A.BAIRRO
	,	B.[NOME] 'CLIENTES' 
	,	B.BAIRRO
FROM [TABELA DE VENDEDORES] A LEFT JOIN [TABELA DE CLIENTES] B
ON A.BAIRRO = B.BAIRRO
WHERE B.[NOME] !=  'NULL'
ORDER BY B.[NOME] ASC