/*COM LEFT JOIN SERÁ FEITO A JUNÇÃO ENTRE A TABELA DA 'ESQUERDA' COM A TABELA DA 'DIREITA', MAS UM POUCO
DIFERENTE DO INNER JOIN. O LEFT JOIN TRARÁ TODA TABELA DA 'ESQUERDA' E SÓ TRARÁ DA TABELA DA 'DIREITA' O QUE FOR INCOMUM ENTRE ELAS...*/
SELECT 
		A.[NOME]
	,	COUNT(*) 
FROM [TABELA DE CLIENTES] A LEFT JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
GROUP BY A.[NOME]

