/*
SUM: SOMA
MAX: VALOR MÁXIMO
MIN: VALOR MÍNIMO
AVG(average): MÉDIA
COUNT: CONTA OCORRÊNCIAS
*/
SELECT 
	ESTADO
  , SUM([LIMITE DE CREDITO]) 'LIMITE DE CRÉDITO'
FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO

SELECT 
	ESTADO
  , AVG([LIMITE DE CREDITO]) 'MÉDIA DE CRÉDITO'
FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO

SELECT 
	EMBALAGEM
  , MAX([PREÇO DE LISTA]) 'PREÇO MÁXIMO'
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT 
	EMBALAGEM
  , MIN([PREÇO DE LISTA]) 'PREÇO MÍNIMO'
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT 
	EMBALAGEM
  , COUNT(*) 'QUANTIDADE'
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM
/*OBS. NÃO ESQUECER DO GROUP BY*/