/*
SUM: SOMA
MAX: VALOR MÁXIMO
MIN: VALOR MÍNIMO
AVG(average): MÉDIA
COUNT: CONTA OCORRÊNCIAS
*/
SELECT 
	ESTADO
  , SUM([LIMITE DE CREDITO]) 'LIMITE DE CRÉDITO'
FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO

SELECT 
	ESTADO
  , AVG([LIMITE DE CREDITO]) 'MÉDIA DE CRÉDITO'
FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO

SELECT 
	EMBALAGEM
  , MAX([PREÇO DE LISTA]) 'PREÇO MÁXIMO'
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT 
	EMBALAGEM
  , MIN([PREÇO DE LISTA]) 'PREÇO MÍNIMO'
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT 
	EMBALAGEM
  , COUNT(*) 'QUANTIDADE'
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT 
	BAIRRO
  , SUM([LIMITE DE CREDITO]) 'LIMITE DE CRÉDITO'
FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' 
GROUP BY BAIRRO
/*
OBS 1. NÃO ESQUECER DO GROUP BY.
OBS 2. SÓ DEVERAR SER ADICIONADO O CAMPO PARA ORDER BY SE ELE ESTIVER DENTRO DO SELECT.
OBS 3. OS CAMPOS CONTIDOS NO SELECT É OBRIGATÓRIO QUE ESTEJA TAMBÉM DENTRO DO ORDER BY
 */