SELECT 
	[CODIGO DO PRODUTO]
  , [NOME DO PRODUTO]
  ,	[EMBALAGEM]
  ,	[TAMANHO]
  ,	[SABOR]
  ,	[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS] 
WHERE [PREÇO DE LISTA] = 4.555 OR [PREÇO DE LISTA] = 4.56 /*CONSULTA FILTRANDO POR PREÇO COM OPERADOR LÓGICO OR*/