SELECT 
	[CODIGO DO PRODUTO]
  , [NOME DO PRODUTO]
  ,	[EMBALAGEM]
  ,	[TAMANHO]
  ,	[SABOR]
  ,	[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS] 
WHERE [PREÇO DE LISTA] > 4.555 AND [PREÇO DE LISTA] < 10 /*CONSULTA FILTRANDO POR PREÇO COM OPERADOR LÓGICO AND*/