SELECT 
    [NOME DO PRODUTO]
  , CASE 
	    WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO' 
	    WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	    ELSE 'PRODUTO BARATO'  /*PARA NOMEAR A COLUNA DO CASE, É NECESSÁRIO SER ATRIBUÍDO O ALIAS APÓS O 'END'*/
FROM [TABELA DE PRODUTOS]

/*O COMANDO CASE NOS MOSTRARÁ UMA CONDIÇÃO VERDADEIRA CASO NENHUMA DAS CONDIÇÕES SEJA VERDADEIRA, ELE EXECUTARÁ O ELSE. 
CASE(CASO) 
    WHEN(QUANDO) <CONDIÇÃO> THEN(ENTÃO) <VALOR 1>
    WHEN <CONDIÇÃO> THEN <VALOR 2>
    ELSE(SENÃO) <VALOR ELSE>
END(FIM)
*/