SELECT 
	  CPF AS IDENTIFICADOR /*"AS IDENTIFICADOR" NOMEIA COLUNA PARA "IDENTIFICADOR". PODEMOS TAMBÉM NÃO COLOCAR O 'AS' QUE IRÁ FUNCIONAR DA MESMA FORMA*/
	, NOME CLIENTE
FROM [TABELA DE CLIENTES] /*SEMPRE COLOCAR ENTRE COLCHETES NOMES DE TABELAS OU CAMPOS QUE TENHA ESPAÇOS OU ACENTOS, ETC.*/
