SELECT DISTINCT 
	EMBALAGEM
  , TAMANHO
FROM [TABELA DE PRODUTOS] 
WHERE[SABOR] = 'Laranja' 
/* OBSERVE QUE NÃO FOI SOLICITADO QUE TRAGA OS DADOS DE SABOR, MAS É POSSÍVEL FAZER O FILTRO*/


SELECT DISTINCT
	EMBALAGEM
  , TAMANHO
  , SABOR 
FROM [TABELA DE PRODUTOS]
/*'DISTINCT' VAI FAZER A COMBINAÇÃO DOS CAMPOS LINHA A LINHA E NÃO VAI PERMITIR REPETIR AS COMBINAÇÕES*/