USE SUCOS_VENDAS
SELECT 
	[CODIGO DO PRODUTO]
  ,	[NOME DO PRODUTO]
  ,	[SABOR]
  ,	[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%LITROS%' 
/* FILTRANDO COM 'LIKE' UTILIZANDO '%' NO INÍCIO E FINAL, BUSCARÁ LITROS EM QUALQUER LOCAL DA ESCRITA, INDEPENDENTE SE ESTÁ NO INÍCIO, MEIO OU FIM*/

USE SUCOS_VENDAS
SELECT 
	[CODIGO DO PRODUTO]
  ,	[NOME DO PRODUTO]
  ,	[SABOR]
  ,	[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE 'LITROS%' 
/* FILTRANDO COM 'LIKE' UTILIZANDO '%' NO FINAL, BUSCARÁ 'LITROS' SOMENTE NO INÍCIO DA ESCRITA*/


USE SUCOS_VENDAS
SELECT 
	[CODIGO DO PRODUTO]
  ,	[NOME DO PRODUTO]
  ,	[SABOR]
  ,	[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%LITROS' 
/* FILTRANDO COM 'LIKE' UTILIZANDO '%' NO INCÍCIO, BUSCARÁ 'LITROS' SOMENTE NO TERMINO*/


