/*SUBCONSULTA NÓS PODEMOS USAR DENTRO DE UM FROM OU DENTRO DE UM CRITÉRIO DE BUSCA.*/

/*SELECIONA OS CAMPOS NOME, BAIRRO, DA TABELA DE CLIENTE, ONDE BAIRRO É IGUAL AOS MESMOS (BAIRROS DA TABELA DOS VENDEDORES)*/
SELECT 
		NOME
	,	BAIRRO 
FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT 
					BAIRRO 
                 FROM [TABELA DE VENDEDORES])



SELECT 
		NOVA_CONSULTA.EMBALAGEM
	,	NOVA_CONSULTA.MAX_PRECO
FROM (SELECT 
			EMBALAGEM
		,	MAX([PREÇO DE LISTA]) AS MAX_PRECO 
	  FROM [TABELA DE PRODUTOS] 
	  GROUP BY EMBALAGEM) NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PRECO <= 5