/*UNION - É IMPORTANTE QUE AS TABELAS QUE SERÃO UNIDAS TENHAM O MESMO NÚMERO E TIPO. O UNION SERVE PARA JUNTAR DUAS CONSULTAS SELECT.*/


SELECT DISTINCT 
	A.BAIRRO 
FROM [TABELA DE CLIENTES] A
UNION
SELECT DISTINCT 
	B.BAIRRO 
FROM [TABELA DE VENDEDORES] B

/*UNION ALL ELIMINA O RESULTADO COM DISTINCT*/
SELECT DISTINCT 
	A.BAIRRO 
FROM [TABELA DE CLIENTES] A
UNION ALL
SELECT DISTINCT 
	B.BAIRRO 
FROM [TABELA DE VENDEDORES] B